### ISSUE TITLE
peer gossip research

### ISSUE THREAD

**Issue by ScottyPoi** [ethereumjs/ultralight#284]
Using this issue to discuss peer gossip research and potential improvements.

**Comment by ScottyPoi** [comment]
Problem: Nodes joining via `add_BootNode`  rarely find each other purely through the `bucketRefresh` / `findNodes` method.

This graph shows the routing table growth of a small set of `bootnodes` and a larger set of nodes that each join via that group of `bootnodes`.  

The routing table of each `bootnodes` grows with each new join, and stay full.  The nodes that join do not effectively find anybody other than bootnodes.

![Screenshot 2022-06-05 at 19-48-37 Explore - Prometheus - Grafana](https://user-images.githubusercontent.com/66335769/172083397-5a401f5b-7b37-4c95-b4fa-16ba46b3f439.png)

At the same time there is a constant flood of `findNodes` messages being sent out all the time.  Even though there are many nodes in the network, the bootnodes are returning `0 ENRS`

This graph is the rate of `findNodes` being sent in the network over the same period.  

 
![Screenshot 2022-06-05 at 19-48-58 Explore - Prometheus - Grafana](https://user-images.githubusercontent.com/66335769/172083680-62f9886f-03a6-4893-95db-9adbaa5f4e70.png)

**Comment by acolytec3** [comment]
I was hoping to see something like this - 
![image](https://user-images.githubusercontent.com/17355484/172197446-9dbd1083-6ec0-4af4-b822-0700017126f3.png)

**Comment by acolytec3** [comment]
But then I added one late joiner and got this
![image](https://user-images.githubusercontent.com/17355484/172197667-5ad4d8df-fce2-4feb-bb47-17ca7341b1d6.png)

**Comment by acolytec3** [comment]
So here's something for us to think about. `FOUNDNODES` contain a maximum of probably 8 ENRs in them (since you can't fit more than 8-9 ENRs in a single payload) so once you get beyond 10 or so nodes in your network, FOUNDNODES responses will only send a subset of the known peers in a given node's table.  So, late joiners, won't be able to get all the "known peers" of a peer they send a `FINDNODES` request to.  As such, now that I've thought it through, it doesn't surprise me that late joiners don't ever get a complete view of the network.  It would be worth discussing further on [this issue](https://github.com/ethereum/portal-network-specs/issues/136) regarding NODES responses.

**Comment by acolytec3** [comment]
One thing we could consider doing to mitigate the limitations of our current setup is randomize which distance we respond to first in the `handleFindNodes` handler.  So if a node requests 240, 241, 242, and 243, we could pick one randomly to pull nodes for first, and that would broaden our connection pull by the powers of `Math.random()`.  There's nothing in the spec that says we have to provide nodes in specific order.

**Comment by ScottyPoi** [comment]
> One thing we could consider doing to mitigate the limitations of our current setup is randomize which distance we respond to first in the handleFindNodes handler.

That's one tweak I haven't tried.  I did a lot of experimenting.  I found some improvements in addBootNode, and bucketRefresh, but nothing that made a significant difference in the overall pattern.  Even making the bucketRefresh more aggressive did not have much affect.


Repeat tests often show individuals among the joining nodes that end up with comparatively more or fewer than peers than the others.  While this may be an artifact of the test setup, it also might suggest "sweet-spots" or "dead-zones" relating to a node's address in the keyspace, or have to do with the density of peers in its local neighboorhood.
 
 I also notice a high frequency of RPC errors during FINDNODES.  I'm looking into ways of using metrics on our logs as well, which may help show patterns in these erros

**Comment by acolytec3** [comment]
>I found some improvements in addBootNode, and bucketRefresh

Are these code fixes we should integrate regardless? I would expect the one bug fix i merged to improve overall peer gossip a bit, I think the bigger problem I outlined in the other issue is going to continue to limit how well a node can populate it's table unless we employ some more aggressive refresh logic, like maybe picking buckets that have 1 node in them in addition to empty ones already and randomizing the order ENRs are returned in

**Comment by acolytec3** [comment]
Just got off the implementers call and got some more insight on this.  One takeaway from @pipermerriam was that it's not as simple as just assuming that all late joining nodes will (or should) automatically find all the same nodes as the bootnodes have.  We should work on refining our strategies around how to populate the routing table on start up (i.e do more than just ask the first bootnode you connect to for a copy of their routing table and hope for the best).  So, maybe as a next step, try out at least the following approaches and see how routing tables look thereafter:

1) Have the startup process do more aggressive lookups than just asking a botonode for all the nodes it knows.  Maybe what we could do is on startup, 
- Ask the boot node for nodes at all distances
- Once we get the initial response from the bootnode, use `bucketRefresh` to look for a node in each empty bucket (working our way in from 256 inward) and do so until we know say at least 10 other nodes and have at least 6 buckets full (picking numbers at random here)
2) Randomize the order in which we select nodes to return in `NODES` messages so that if a node sends the same FINDNODES request twice, it likely gets different nodes each time (unless we have 8 or less nodes in our table, in which case it wouldn't matter).

One way to test out this process would be to run a devnet, give it say 5 minutes for nodes to try and find each other using whatever strategies (either our current naive one or one of these new ones - or others) and then pick a random non-bootnode and try to do a `nodeLookup` for all nodes in the network and see how many we are able to find via recursive lookup.  That will give us a sense for how healthy the network is (i.e., if we are able to find most or all the nodes every time, then we have reasonably good strategies for keeping routing tables fresh)
